pipeline {
    agent {
        node {
            label 'jenkins-slave-omkar'
        }
    }

    stages {
        stage('Hello') {
            steps {
                bat 'C:\\Users\\TURBO\\Desktop\\OMKAR\\PROGRAMMING\\Practice_Omkar\\Exercise\\02\\script.bat'
            }
        }
    }
}
