pipeline {
    agent {
        node {
            label 'jenkins-slave-omkar'
        }
    }

    stages {
        stage('build') {
            steps {
                echo env.STAGE_NAME
            }
        }
        stage('test') {
            steps {
                echo env.STAGE_NAME
            }
        }
    }
}
